name: functions

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: th22ih4ciw4cg01celloFunctions
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # アップロードするディレクトリ（現在はルートディレクトリ）
  NODE_VERSION: "16.x"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONS_CREDENTIALS }} # プロファイラ
