name: functions

# main ブランチに何らかの commit が追加されたら走らせる
on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: HAL-TH22-IH4C-IW4C-G01-functions01-yoshida # functionsの名前。書き換えてください
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # アップロードするディレクトリ。書き換えてください（現在はルートディレクトリすべてをデプロイしている）
  NODE_VERSION: "16.x" # nodeのバージョンを指定。書き換えてください

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        run: npm install

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build using npm
        run: npm run build --if-present

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Test using npm
        run: npm run test --if-present

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup, build, test]
    steps:
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.FUNCTIONS_NAGIDERBY }} # プロファイラを登録したNAMEを指定してください
